### PR TITLE
force use of system cuda installation

### LINKED ISSUE #38: Use system Nvidia install rather than binary builder version
This is causing issues with large logs and timeout errors against the Github api during job finalization.

### PR DESCRIPTION
**Pull request by jakebolewski**
Closes #38

### CODE REVIEW

**Comment by simonbyrne** [comment]
You'll need to update all the cpu ones as well, as we load the CuArrays package in both cases.

**Comment by jakebolewski** [comment]
Updated to add the cpu-init scripts

**Comment by simonbyrne** [comment]
I think you'll need to add it to all scripts, since it is used at module `__init__` time (which is why it is causing a problem).

**Comment by simonbyrne** [comment]
need `perf-cpu` as well.

**Comment by jakebolewski** [comment]
I think Ive now added all of them

**Comment by simonbyrne** [comment]
ah, `perf-gpu.sh` is missing (there should be 4 `perf` and 6 `test` ones)

**Pull request merged**
